apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpt-huggingface
  labels:
    app: gpt-hf-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gpt-hf-pod
  template:
    metadata:
      labels:
        app: gpt-hf-pod
    spec:
      containers:
        - name: gptcontainer
          image: junjiewee/fastapi-app:latest
          ports:
            - containerPort: 8000
